### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by developerdavi** [developerdavi/express-api-template#1]
### Todo
- [ ] Tests (using Jest or Mocha)
- [ ] SQL database (MySQL/Postegres/etc)
- [ ] Development database (using SQLite)
- [ ] Query/body schema verification (Yup or similar)
